name = "CCSTwin"
uuid = "2b1ad213-65ee-458c-847d-e139f9fe9548"
authors = ["Jerell James <jerell1998@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
